apiVersion: v1
kind: Pod
metadata:
  name: my-resource-pod
  labels:
    env: dev
spec:
  containers:
    - name: resource
      image: nginx
      ports:
        - containerPort: 80
        
      command: ["stress", "--vm", "1", "--vm-bytes", "155M"]  
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi



